apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ovb6wz47e-python
  janus-idp.io/tekton: ovb6wz47e-python
  backstage.io/kubernetes-id: ovb6wz47e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ovb6wz47e-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
