apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ovb6wz47e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ovb6wz47e-python 
  name: ovb6wz47e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ovb6wz47e-python 
